@echo off
echo Fixing Prisma schema issues...

echo Stopping development server...
taskkill /f /im node.exe >nul 2>&1

echo Generating Prisma client...
npx prisma generate

echo Starting development server...
npm run dev
