#!/bin/bash

# MongoDB Atlas Setup Guide for NaijaLingua
# This script provides step-by-step instructions

echo "================================"
echo "MongoDB Atlas Setup Guide"
echo "================================"
echo ""
echo "Follow these steps to set up a new MongoDB Atlas cluster:"
echo ""
echo "1. Go to https://cloud.mongodb.com/"
echo "   - Sign in or create a free account"
echo ""
echo "2. Create a New Cluster:"
echo "   - Click 'Build a Database'"
echo "   - Choose FREE tier (M0)"
echo "   - Select a cloud provider (AWS recommended)"
echo "   - Choose a region close to your users"
echo "   - Name your cluster (e.g., 'naijalingua-cluster')"
echo "   - Click 'Create'"
echo ""
echo "3. Set Up Database Access:"
echo "   - Go to 'Database Access' (left sidebar)"
echo "   - Click 'Add New Database User'"
echo "   - Create username and password"
echo "   - Set role to 'Atlas Admin' or 'Read and write to any database'"
echo "   - Click 'Add User'"
echo ""
echo "4. Set Up Network Access:"
echo "   - Go to 'Network Access' (left sidebar)"
echo "   - Click 'Add IP Address'"
echo "   - Choose 'Allow Access from Anywhere' (0.0.0.0/0)"
echo "   - Click 'Confirm'"
echo ""
echo "5. Get Connection String:"
echo "   - Go to 'Database' (left sidebar)"
echo "   - Click 'Connect' on your cluster"
echo "   - Choose 'Connect your application'"
echo "   - Copy the connection string"
echo "   - Replace <password> with your database user password"
echo "   - Replace <database> with 'naijalingua'"
echo ""
echo "6. Update Your .env File:"
echo "   DATABASE_URL=\"mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/naijalingua?retryWrites=true&w=majority\""
echo ""
echo "7. Update Vercel Environment Variables:"
echo "   - Go to your Vercel dashboard"
echo "   - Project Settings > Environment Variables"
echo "   - Update DATABASE_URL with the new connection string"
echo "   - Redeploy your application"
echo ""
echo "================================"
echo "After setup, run: node test-mongodb-connection.cjs"
echo "================================"
