import { redirect } from '@sveltejs/kit';
import { db } from '$lib/db';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async ({ locals }) => {
	if (!locals.user || locals.user.role !== 'ADMIN') {
		throw redirect(303, '/auth/login');
	}

	// Get existing auto-generated courses
	const autoGeneratedCourses = await db.course.findMany({
		where: {
			tags: {
				has: 'auto-generated'
			}
		},
		include: {
			_count: {
				select: {
					lessons: true,
					enrollments: true
				}
			}
		},
		orderBy: {
			createdAt: 'desc'
		}
	});

	// Get generation statistics
	const stats = {
		totalGenerated: autoGeneratedCourses.length,
		published: autoGeneratedCourses.filter(c => c.isPublished).length,
		totalEnrollments: autoGeneratedCourses.reduce((sum, c) => sum + c._count.enrollments, 0),
		languages: [...new Set(autoGeneratedCourses.map(c => c.language))],
		levels: [...new Set(autoGeneratedCourses.map(c => c.level))]
	};

	return {
		autoGeneratedCourses,
		stats
	};
};
